#!/bin/sh

function conf() { 
	# This is bad.  For instance, if $2 evaluates to 'echo rm -rf /'...  We
	# can't just grep out of /etc/passwd, because it doesn't contain user home
	# directory information on OS X.  So, don't create any user accounts with
	# weird names.  It'd also be a good idea to create a separate
	# 'terminal-screensaver' user with write privileges to nothing other than
	# /var/run/terminal-screensaver .
	eval homedir=~$2
	grep $1 $homedir/.terminal-screensaver.conf \
	| awk '{for (i=2;i<=NF;i++) {printf "%s%s",(i>2?" ":""), $i}; printf "\n"}'
}

screensaver=`conf screensaver-command`
echo "screensaver $screensaver called in process $terminal_screensaver_pid"
exec $screensaver

