#!/bin/sh

function conf() {
	# Improved function still relies on tilde expansion, but should be safe.
	# Feel free to create user accounts named '`rm -rf /`' if you like :)
	# This also only returns the first match in the file, rather than
	# potentially returning a confusing mess if multiple options match.
	# Exception handling is non-existant, but that's nothing new.
	# Thanks to cut's nature, matching lines containing no spaces
	# will be returned unaltered.
	if [ "x$2" = "x" ]; then
		homedir=~
	else
		eval homedir="$(printf "~%q" "$2")"
	fi
	[ -d "$homedir" ] || return 2 # user has a home directory?
	[ -e "$homedir/.terminal-screensaver.conf" ] || return 3 # that directory has a config file?
	[ -O "$homedir/.terminal-screensaver.conf" ] || return 4 # that config file is safe?
	grep -m 1 -e "^$1" -- "$homedir/.terminal-screensaver.conf" | cut -d' ' -f2-
}

screensaver="`conf screensaver-command`"
#echo "screensaver $screensaver called in process $terminal_screensaver_pid"
exec $screensaver

