#!/bin/zsh

while :; do
	echo "screensaverd called"
	for pid in `ls pids`; do
		echo "checking $pid"
		if test `find pids/$pid -mmin +1`; then
			echo "too old"
			kill -SIGALRM $pid
		fi
	done
	sleep 15
done

